navigation:
  - text: Santo Rosário
    url: /rosario.html
  - text: Saltério
    url: /salterio.html
  - text: Pequeno Ofício de Nossa Senhora
    url: /oficio.html
  - text: Antífonas de Nossa Senhora
    url: /antifonas.html
  - text: Baptismo
    url: /baptismo.html

exclude:
  [
    "missa/missal1962",
    "missa/resources",
    "missa/README.md",
    "missa/Pipfile.lock",
    "missa/Pipfile",
    "missa/gen_static_data.sh",
    "missa/Dockerfile",
    "missa/tests",
    "missa/img",
    "node_modules",
    ".vscode",
    ".vs",
    ".netlify",
  ]
